# Generated by Django 5.1.2 on 2024-11-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogpost',
            name='tags',
            field=models.CharField(max_length=127),
        ),
    ]
