# Generated by Django 5.1.2 on 2024-11-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog_app', '0006_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='vlogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='tags',
            field=models.ManyToManyField(to='vlog_app.categories'),
        ),
    ]
