# Generated by Django 5.1.2 on 2024-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog_app', '0007_alter_categories_id_remove_vlogpost_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogpost',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
